### PR TITLE
Add timestamp to icons sprite url in stylesheet

### PR DESCRIPTION
**Pull request by zipp3r**
Hello, guys! Hi, guys. I have added timestamp to icons sprite url to prevent browsers from caching the file as this caused incorrect menu icons. (http://take.ms/7k2CK)

### CODE REVIEW

**Comment by zipp3r** [comment]
Anybody here?

**Comment by mlewand** [comment]
Sorry for not hearing from us for a long time. Actually this is something that we're looking for to fix [#10685](http://dev.ckeditor.com/ticket/10685).

The only problem is that it causes tests to fail, but we can carry it from here! @Tade0 I'll ask you to change the tests so we have no regressions there.

**Comment by mlewand** [comment]
I've rebased @zipp3r 's commit to the latest master in the [t/7](https://github.com/ckeditor/ckbuilder/tree/t/7) branch.

**Comment by mlewand** [comment]
In order to have passing tests with fixtures we need to stub timestamp in few places. We won't stub it globally as it could make mess, but we'll attempt to check that in #17 and if possible apply stubbed timestamp to all tests.

**Comment by mlewand** [comment]
LGTM, R+ - merged with d2155771c06a5a7437f30be9f3b42ef60bc184c2.

@zipp3r thank you for the contribution!

**Comment by zipp3r** [comment]
Thanks a lot! As I'm understand this changes already in master?

**Comment by mlewand** [comment]
Well not just yet, we need to update CKBuilder in CKEditor build scripts. Watch [#10685](http://dev.ckeditor.com/ticket/10685) for updates, it's planned for 4.6.0 release.

**Pull request closed without merging**
